spring.application.name=eventnexus

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
